name: Go Inspect
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  execute:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Check environment.
        run: |
          ls -ltra
          python --version
          pip --version
      - name: Setup Graphviz
        run: |
          apk add --update --no-cache graphviz
      - name: Install dependencies.
        run: |
          pip install -r requirements.txt
      - name: Execute script.
        env:
          REPOS: ${{ secrets.REPOS }}
          WORKFLOW_GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        run: |
          python app.py
      - name: Save Results
        uses: actions/upload-artifact@v3
        with:
          name: content
          path: Workflows-*.*